let site and domain be a cli parameter

diff --git a/addsite b/addsite
--- a/addsite
+++ b/addsite
@@ -5,6 +5,19 @@ DBPASS=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c12`
 SFTPPASS=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c12`
 ROOTDIR=/var/www/
 
+uasge() {
+  echo "usage: $0 <sitename> <domain>"
+  exit
+}
+
+die() {
+  echo "ERROR: $1"
+  exit 1
+}
+
+if [ "$1" = "-h" ]; then
+  usage
+fi
 while true
 do
 	echo "Select database server type:
@@ -33,10 +46,19 @@ if [ "$DBPACKAGE" = "postgresql postgresql-contrib" ]; then
 fi
 
 # Input site name and domain name
-echo -n "Enter your site name (spaces and special symbols are not allowed):"
-read SITENAME
-echo -n "Enter your domain name:"
-read DOMAIN
+if [ "$1" = "" ]; then
+  echo -n "Enter your site name (spaces and special symbols are not allowed): "
+  read SITENAME
+else
+  SITENAME=$1
+fi
+if [ "$2" = "" ]; then
+  echo -n "Enter your domain name: "
+  read DOMAIN
+else
+  DOMAIN=$2
+fi
+
 
 HOMEDIR=${ROOTDIR}${SITENAME}
 # Check if the ${HOMEDIR} dir exists
